import dj_database_url
import os
from dotenv import load_dotenv
from pathlib import Path
from utils.symbols import success, error, warning, loading, info

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
from logging.handlers import RotatingFileHandler
from pythonjsonlogger import jsonlogger

from utils.logs import RequestContextFilter

load_dotenv(os.path.join(BASE_DIR, ".env"))

try:
    """
    Django settings for core project.

    Generated by 'django-admin startproject' using Django 5.2.5.

    For more information on this file, see
    https://docs.djangoproject.com/en/5.2/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/5.2/ref/settings/
    """

    print(loading("Loading base settings..."))

    if os.path.exists(os.path.join(BASE_DIR, ".env")):
        print(success(".env file loaded successfully."))
    else:
        print(warning(".env file not found. Proceeding without it."))

    # Create logs directory if it doesn't exist
    logs_dir = os.path.join(BASE_DIR, "logs")
    os.makedirs(logs_dir, exist_ok=True)

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "rest_framework",
        "rest_framework_simplejwt",
        "dj_rest_auth",
        "account",
        "api",
        "rest_framework.authtoken",
        "rest_framework_simplejwt.token_blacklist",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "core.middleware.RequestContextMiddlewares.RequestContextMiddleware",
        "core.middleware.JWTFromCookieMiddleware.JWTFromCookieMiddleware",
    ]

    ROOT_URLCONF = "core.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [BASE_DIR / "templates"],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "core.wsgi.application"

    # Password validation
    # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/5.2/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/5.2/howto/static-files/

    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"
    STATICFILES_DIRS = [BASE_DIR / "static"]

    # Default primary key field type
    # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    AUTHENTICATION_BACKENDS = [
        "account.authentication.EmailBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

    REST_FRAMEWORK = {
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",
            "rest_framework.renderers.TemplateHTMLRenderer",
        ],
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ],
    }

    AUTH_USER_MODEL = "account.CustomUser"

    from datetime import timedelta

    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
        "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    }

    DATABASES = {"default": dj_database_url.config(default=os.getenv("DATABASE_URL"))}

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {service} {user_id} {request_path} {message}",
                "style": "{",
                "defaults": {
                    "service": "UNKNOWN",
                    "user_id": "anonymous",
                    "request_path": "unknown",
                },
            },
            "simple": {
                "format": "{levelname} {service} {message}",
                "style": "{",
                "defaults": {"service": "UNKNOWN"},
            },
            "json": {
                "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
                "format": "%(levelname)s %(asctime)s %(module)s %(service)s %(user_id)s %(request_path)s %(message)s",
            },
        },
        "filters": {
            "request_context": {
                "()": RequestContextFilter,
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "simple",
                "filters": ["request_context"],
            },
            "file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(BASE_DIR, "logs", "server.log"),
                "maxBytes": 1024 * 1024 * 5,  # 5 MB per file
                "backupCount": 5,  # Keep 5 backup files
                "formatter": "verbose",
                "filters": ["request_context"],
            },
            "json_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": os.path.join(BASE_DIR, "logs", "server.json.log"),
                "maxBytes": 1024 * 1024 * 5,
                "backupCount": 5,
                "formatter": "json",
                "filters": ["request_context"],
            },
        },
        "loggers": {
            "": {
                "handlers": ["console", "file", "json_file"],
                "level": "INFO",
                "propagate": False,
            },
            "account": {
                "handlers": ["console", "file", "json_file"],
                "level": "DEBUG",  # Capture DEBUG for development
                "propagate": False,
            },
            "api": {
                "handlers": ["console", "file", "json_file"],
                "level": "INFO",
                "propagate": False,
            },
            "services.email": {
                "handlers": ["console", "file", "json_file"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }

    CSRF_TRUSTED_ORIGINS = [
        "https://crosscode.robinrajan.com",
        "http://crosscode.robinrajan.com",
    ]

    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")  # Your Gmail address
    EMAIL_HOST_PASSWORD = os.getenv(
        "EMAIL_HOST_PASSWORD"
    )  # The 16-character App Password from step 2
    DEFAULT_FROM_EMAIL = (
        "Cross Code <your-email@gmail.com>"  # Optional: for consistent sender display
    )
    DOMAIN = os.getenv("DOMAIN", "http://localhost:8000")

    print(success("Base settings loaded successfully."))

except ImportError as e:
    print(error(f"Error loading base settings: {str(e)}"))
    raise str(e)

except Exception as e:
    print(error(f"Unexpected error loading base settings: {str(e)}"))
    raise str(e)
